-----window functions

select * from product;

select *,
FIRST_VALUE(PRODUCT_NAME) OVER (PARTITION BY PRODUCT_CATEGORY  ORDER BY PRICE DESC) AS EXPENSIVE_PRODUCT,
LAST_VALUE(PRODUCT_NAME) OVER (PARTITION BY PRODUCT_CATEGORY  ORDER BY PRICE DESC) AS CHEAP_PRODUCT
from product;

select *,
FIRST_VALUE(PRODUCT_NAME) OVER (PARTITION BY PRODUCT_CATEGORY  ORDER BY PRICE DESC) AS EXPENSIVE_PRODUCT,
LAST_VALUE(PRODUCT_NAME) OVER (PARTITION BY PRODUCT_CATEGORY 
ORDER BY PRICE DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS CHEAP_PRODUCT
from product;

SELECT P.*,
       FIRST_VALUE(PRODUCT_NAME) OVER W  AS EXPENSIVE_PRODUCT,
       LAST_VALUE(PRODUCT_NAME) OVER W   AS CHEAP_PRODUCT
FROM product P
WINDOW W AS (
  PARTITION BY PRODUCT_CATEGORY
  ORDER BY PRICE DESC
  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
);


SELECT
  p.*,
  FIRST_VALUE(PRODUCT_NAME) OVER (
    PARTITION BY PRODUCT_CATEGORY
    ORDER BY PRICE DESC, PRODUCT_NAME
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
  ) AS EXPENSIVE_PRODUCT,
  LAST_VALUE(PRODUCT_NAME) OVER (
    PARTITION BY PRODUCT_CATEGORY
    ORDER BY PRICE DESC, PRODUCT_NAME
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
  ) AS CHEAP_PRODUCT
FROM product p;

SELECT
  p.*,
  MAX_BY(PRODUCT_NAME, PRICE) OVER (PARTITION BY PRODUCT_CATEGORY) AS EXPENSIVE_PRODUCT,
  MIN_BY(PRODUCT_NAME, PRICE) OVER (PARTITION BY PRODUCT_CATEGORY) AS CHEAP_PRODUCT
FROM product p;

SELECT
  p.*,
  NTH_VALUE(PRODUCT_NAME,2) OVER (
    PARTITION BY PRODUCT_CATEGORY
    ORDER BY PRICE DESC, PRODUCT_NAME
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SECOND_HIGHEST_PRODUCT
FROM product p;

SELECT *,
ntile(3) over (order by price desc)  as buckets
FROM PRODUCT
WHERE PRODUCT_CATEGORY='Phone';;


select product_name,
case when x.buckets =1 then 'expensive phones'
     when x.buckets =2 then 'med range phones'
     when x.buckets =3 then 'cheaper range phones' end as phone_category
from (
SELECT *,
ntile(3) over (order by price desc)  as buckets
FROM PRODUCT
WHERE PRODUCT_CATEGORY='Phone') x ;
